"""add index for bm25 search

Revision ID: 08778a3efc97
Revises: 512742901a42
Create Date: 2026-01-14 13:28:46.005607
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "08778a3efc97"
down_revision = "512742901a42"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "idx_chunks_bm25",
        "chunks",
        ["id", "content"],
        unique=False,
        postgresql_using="bm25",
        postgresql_with={"key_field": "id"},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_chunks_bm25",
        table_name="chunks",
        postgresql_using="bm25",
        postgresql_with={"key_field": "id"},
    )
    # ### end Alembic commands ###
