"""change metadata field name to avoid attribute name clash

Revision ID: 1380a1a0ce5f
Revises: 20240109_000001
Create Date: 2026-01-13 07:01:52.699857
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision = "1380a1a0ce5f"
down_revision = "20240109_000001"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chunks",
        sa.Column(
            "chunk_metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
    )
    op.alter_column(
        "chunks",
        "content",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=False,
    )
    op.drop_index(op.f("chunks_document_id_idx"), table_name="chunks")
    op.create_index("idx_chunks_document_id", "chunks", ["document_id"], unique=False)
    op.create_index(
        "idx_chunks_embedding_hnsw",
        "chunks",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.create_unique_constraint(
        "uq_chunks_document_chunk_index", "chunks", ["document_id", "chunk_index"]
    )
    op.drop_column("chunks", "metadata")
    op.add_column(
        "documents",
        sa.Column(
            "doc_metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
    )
    op.add_column(
        "documents", sa.Column("embedding_model", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
    )
    op.alter_column(
        "documents",
        "source",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=True,
    )
    op.alter_column(
        "documents",
        "title",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=True,
    )
    op.create_index(op.f("ix_documents_source"), "documents", ["source"], unique=False)
    op.drop_column("documents", "metadata")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "documents",
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_index(op.f("ix_documents_source"), table_name="documents")
    op.alter_column(
        "documents",
        "title",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        "documents",
        "source",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.drop_column("documents", "embedding_model")
    op.drop_column("documents", "doc_metadata")
    op.add_column(
        "chunks",
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint("uq_chunks_document_chunk_index", "chunks", type_="unique")
    op.drop_index(
        "idx_chunks_embedding_hnsw",
        table_name="chunks",
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.drop_index("idx_chunks_document_id", table_name="chunks")
    op.create_index(op.f("chunks_document_id_idx"), "chunks", ["document_id"], unique=False)
    op.alter_column(
        "chunks",
        "content",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.drop_column("chunks", "chunk_metadata")
    # ### end Alembic commands ###
